spring:
  application:
    name: sinsa_payments

#  datasource:
#    url: jdbc:h2:tcp://localhost/~/freepoint
#    username: sa
#    password:
#    driverClassName: org.h2.Driver
  datasource:
    read:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3308/mysql_write_point
      username: root
      password: "1234"
      read-only: true
      maximun-pool-size: 3
      minimun-pool-size: 2
      idle-timeout: 10000
    write:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3307/mysql_write_point
      username: root
      password: "1234"
      read-only: false
      maximun-pool-size: 3
      minimun-pool-size: 2
      idle-timeout: 10000

  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  #      default_batch_fetch_size: 100
#    config:
#      on-profile: local
#  jpa:
#    defer-datasource-initialization: true
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: create
#    properties:
#      dialect: org.hibernate.dialect.H2Dialect
#      format_sql: true
#    show_sql: true

#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  sql:
#    init:
#      mode: always

redis:
  host: localhost
  port: 6379